import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NavlessLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mx-auto min-h-screen flex flex-col bg-white overflow-x-hidden" style={{ maxWidth: 'var(--max-width-mobile)' }}>
      <main className="flex-1 overflow-x-hidden">
        {children}
      </main>
    </div>
  );
}