import type { Metadata } from "next";
import TabBar from "../components/ui/TabBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NavLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mx-auto min-h-screen flex flex-col bg-white overflow-x-hidden" style={{ maxWidth: 'var(--max-width-mobile)' }}>
      <main className="flex-1 px-8 pt-9 overflow-x-hidden">
        {children}
      </main>
      <TabBar />
    </div>
  );
}
