import type { Metadata } from "next";
import "./globals.css";
import { TabBarGradientProvider } from "./components/ui/tabBar/TabBarGradientContext";
import TabBarGradient from "./components/ui/tabBar/TabBarGradient";
import ReactQueryProvider from "./providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link
          rel="stylesheet"
          as="style"
          crossOrigin="anonymous"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css"
        />
      </head>
      <body className="antialiased bg-white">
        <ReactQueryProvider>
          <TabBarGradientProvider>
            {children}
            <TabBarGradient />
          </TabBarGradientProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
